;*********************************************************************
;filename:      draw_boxplot.ncl
;input_file:   area_avrg_ts_winter.nc
;                                            by Ql_Ren
;                                           2018/03/06
;*********************************************************************************
begin
path     = "/home/ys17-19/renql/project/2017downscaling"
fileout  = path + "/regression/mdata/" + "area_avrg_ts_winter.nc" 
